# Generated by Django 4.0.4 on 2022-08-15 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_uplodedimgs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Uplodedimgs',
        ),
    ]
