# Generated by Django 4.0.4 on 2022-08-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_uploadedimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimg',
            name='name',
            field=models.CharField(max_length=50, unique=b'I01\n', verbose_name='name'),
        ),
    ]
